name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  success-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C02H851AXQF\",\"text\":\"Testing Github Slack Integration on every push\"}'
