name: Slack Notify

on:
  pull:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Send Slack Notification
        uses: keithalpichi/slack-action@0.0.6
        with: 
          template: steps1
          description: Guru Core Test
          title: optional Title
          status: ${{ toJSON(steps) }}
