name: Slack Notify

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: https://github.com/wartek-noviadi/guru-core-qa
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#guru-core-qa'
        if: always()
      - name: Checkout
        uses: actions/checkout@v2
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
          message: 'You rock!'
        if: always()
